### PR TITLE
Add logo

### LINKED ISSUE #11: Logo

### PR DESCRIPTION
**Pull request by ykzts**
Resolve #11

### CODE REVIEW

**Comment by richardbmx** [comment]
@ykzts  I'm working in it

**Comment by richardbmx** [comment]
I present two proposals of possible logos, both in horizontal and vertical versions with variation of a single color and in black. I use the silhouette of the universal chat logo to give an identification to the project. If you want some change you can request it without problem, and if you want one of these two proposals I can send you a folder of google drive with all the necessary files to use it.

logo 99

**Comment by ykzts** [comment]
Umm...Neither seems to be my preference.

**Comment by ykzts** [comment]
Not planned. However, there is the possibility of adopting the alternative I like if there is one.

**Comment by richardbmx** [comment]
@ykzts  ok perfect I will work on other proposals to present them

**Pull request merged**
